language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

cache:
  directories:
    - vendor

env:
  matrix:
    - PREFER=""
    - PREFER="--prefer-lowest --prefer-stable"

matrix:
  fast_finish: true
  allow_failures:
    - php: '5.4'
    - php: '5.5'
    - php: nightly

before_script:
  - tests/prepare

script:
  - vendor/phpcs
  - vendor/phpunit --testdox || vendor/phpunit --verbose
